# Configuration file for harmonizing datasets.
# Current settings are tailored for NEMO output, interpolating multiple grid variables to the T grid.
# Transformations are applied sequentially: output of one step is input for the next.
# Example: after interpolation and combination, you get a single dataset; renaming is then applied to this combined dataset.

# =============================================
# Input data configuration
# Specify files using a glob pattern or single file.
# =============================================
input_data:
  grid_file_paths:
    U:      /project/6007519/pmyers/ANHA4/ANHA4-EPM522-S/ANHA4-EPM522_y20**m**d**_gridU.nc
    V:      /project/6007519/pmyers/ANHA4/ANHA4-EPM522-S/ANHA4-EPM522_y20**m**d**_gridV.nc
    T:      /project/6007519/pmyers/ANHA4/ANHA4-EPM522-S/ANHA4-EPM522_y20**m**d**_gridT.nc
    W:      /project/6007519/pmyers/ANHA4/ANHA4-EPM522-S/ANHA4-EPM522_y20**m**d**_gridW.nc
    icemod: /project/6007519/pmyers/ANHA4/ANHA4-EPM522-S/ANHA4-EPM522_y20**m**d**_icemod.nc
  additonal_paths:
    mask:   /home/caion/projects/rrg-pmyers-ad/ANHA4-I/ANHA4_mesh_mask.nc 

# =============================================
# Data transformations
# Specify transformations to apply to input data.
# =============================================
transformations:
  combine_period: year # day, month, year
  # Interpolation to a common grid (target: T grid).
  # target_reference_variable provides dimensions for interpolation.
  # source_var: variable to interpolate. dims_mapping: maps source dimensions to target dimensions.
  interpolation:
    target_grid: T
    target_reference_variable: "votemper"
    variables:
      U:
        - source_var: "vozocrtx"
          dims_mapping:
            x_grid_U: x_grid_T
      V:
        - source_var: "vomecrty"
          dims_mapping:
            x_grid_V: x_grid_T
      W:
        - source_var: "vovecrtz"
          dims_mapping:
            grid_W_3D_inner: deptht
        
  # Combine additional datasets with the interpolated dataset.
  # Here, the icemod dataset is combined, mapping its variables to the target grid.
  combination:
    icemod:
      variables:
        iicevelu: 
        iicevelv:
        ileadfra:
          dims_mapping:
            y_grid_T_2D_inner: y_grid_T
            x_grid_T_2D_inner: x_grid_T
        iicethic:
          dims_mapping:
            y_grid_T_2D_inner: y_grid_T
            x_grid_T_2D_inner: x_grid_T

  # Renaming of variables, coordinates, and dimensions.
  # This step occurs after interpolation and combination (i.e., on the combined dataset).
  renaming:
    deptht: depth
    x_grid_T: X
    y_grid_T: Y
    x_grid_T_2D_inner: X
    y_grid_T_2D_inner: Y
    nav_lat_grid_T: lat
    nav_lon_grid_T: lon
    votemper: temperature
    sohmld: ocean_mixed_layer_thickness
    vosaline: salinity
    vomecrty: v
    vozocrtx: u
    vovecrtz: w
    iicevelu: ice_u
    iicevelv: ice_v
    iicethic: ice_thickness
    ileadfra: ice_concentration

  # Attributes to add to file and variables.
  attributes_to_add:
    file: 
      title: NEMO ANHA4-EPM520
      source: NEMO ocean model
    variables:
      u:
        units: "meter second-1"
        standard_name: "x_sea_water_velocity"
      v:
        units: "meter second-1"
        standard_name: "y_sea_water_velocity"
      w:
        standard_name: "upward_sea_water_velocity"
        long_name: "ocean vertical velocity"
        units: "meter second-1"
        time: "time_counter"
      sossheig:
        standard_name: sea_surface_elevation
      ocean_mixed_layer_thickness:
        standard_name: ocean_mixed_layer_thickness
        units: m
      depth:
        standard_name: depth
        long_name: depth
        axis: Z
      temperature:
        units: Celsius
      salinity:
        standard_name: sea_water_salinity
      ice_u:
        standard_name: x_sea_ice_velocity
      ice_v:
        standard_name: y_sea_ice_velocity
      mbathy:
        standard_name: sea_floor_depth_below_sea_level
      tmask:
        standard_name: land_binary_mask
      

  # Coordinates to add to each variable in the combined dataset.
  coords_to_add:
    u: ["X", "Y"]
    v: ["X", "Y"]
    w: ["X", "Y"]
    temperature: ["X", "Y"]
    salinity: ["X", "Y"]
    ocean_mixed_layer_thickness: ["X", "Y"]
    ice_u: ["X", "Y"]
    ice_v: ["X", "Y"]

  # Slice dataset to region of interest.
  slicing:
    region_of_interest:
      X: [0, 593]
      Y: [330, 799]

  # Keep only selected variables and coordinates.
  keep:
    variables: ["u", "v", "w", "temperature", "salinity", "depth", "ice_u", "ice_v", "ice_thickness", "ice_concentration", "sossheig", "ocean_mixed_layer_thickness", "mbathy", "tmask"]
    coords: ["X", "Y", "depth", "time_counter", "time_centered", "lon", "lat"]

# =============================================
# Xarray
# =============================================
xarray:
  engine: netcdf4               # Engine for reading NetCDF
  reader:
    combine: by_coords       # Combine multiple files by coordinates
    data_vars: minimal           # Load all variables
  chunks:
    time_counter: 100

# =============================================
# Output configuration
# =============================================
output: 
  directory: "output/"
  file_name: "combined_ds"
